# Generated by Django 3.0.5 on 2020-05-08 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(help_text='请输入“男”或者“女”', max_length=1, validators=[django.core.validators.RegexValidator(message='请确保性别格式正确！', regex="^['男'|'女']$")], verbose_name='性别')),
                ('age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='年龄')),
                ('address', models.CharField(max_length=50, verbose_name='住址')),
                ('phone', models.CharField(help_text='请输入中国大陆11位手机号', max_length=11, validators=[django.core.validators.RegexValidator(message='请确保手机号格式正确！', regex='^1(3|5|7|8|9)\\d{9}$')], verbose_name='联系方式（手机）')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(help_text='请输入纯数字ISBN（不带横杠）', max_length=13, validators=[django.core.validators.RegexValidator(message='请确保ISBN格式正确！', regex='^\\d{13}$')], verbose_name='ISBN号')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('language', models.CharField(default='汉语', max_length=10, verbose_name='语言')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('publisher', models.CharField(max_length=30, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(999.99, message='最高999.99元'), django.core.validators.MinValueValidator(0.01, message='最低0.01元')], verbose_name='售价')),
                ('inventory', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='当前库存')),
            ],
            options={
                'verbose_name': '图书信息',
                'verbose_name_plural': '图书信息',
                'ordering': ['name', 'author', 'publisher'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
                'ordering': ['name', 'country'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_out', models.CharField(help_text='请输入“进货”或者“出货”', max_length=2, validators=[django.core.validators.RegexValidator(message='请确保输入“进货”或者“出货”之一！', regex='^(?:进货|出货)$')], verbose_name='进货/出货')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成交金额')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='成交数量')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='成交时间')),
                ('paid', models.CharField(help_text='请输入“未付款“、”已付款“、”已退货“之一', max_length=3, validators=[django.core.validators.RegexValidator(message='请确保输入“未付款“、”已付款“、”已退货“之一！', regex='^(?:未付款|已付款|已退货)$')], verbose_name='未付款/已付款/已退货')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookstore.Book', verbose_name='商品')),
                ('ruler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookstore.Admin', verbose_name='执行交易的管理员')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-time'],
            },
        ),
    ]
