# Generated by Django 3.0.5 on 2020-05-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookstore.Publisher', verbose_name='出版社'),
        ),
    ]
