# Generated by Django 3.0.5 on 2020-05-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='nationality',
        ),
    ]
