# Generated by Django 3.0.5 on 2020-05-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20200510_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name', 'publisher'], 'verbose_name': '图书信息', 'verbose_name_plural': '图书信息'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
