# Generated by Django 3.0.5 on 2020-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20200510_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='bookstore.Category', verbose_name='类别'),
        ),
    ]
