# Generated by Django 3.0.5 on 2020-05-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=100, null=True, verbose_name='简介'),
        ),
    ]
