# Generated by Django 3.0.5 on 2020-05-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='懒狗管理员没有留下任何摘要，是不是可以爬了？', max_length=100, verbose_name='简介'),
        ),
    ]
